### ISSUE TITLE
Laravel version

### ISSUE THREAD

**Issue by kullarkert** [kbs1/laravel-encrypted-api#2]
I think it should require laravel/framework and not laravel/laravel, since Laravel/Laravel is the application template/skeleton.

Tried to install and got error:

  Problem 1
    - Installation request for kbs1/laravel-encrypted-api v1.0 -> satisfiable by kbs1/laravel-encrypted-api[v1.0].
    - kbs1/laravel-encrypted-api v1.0 requires laravel/laravel >=5.4 -> no matching package found.

**Comment by kbs1** [comment]
Thank you, fixed, this package will be obsoleted in a few months, so please keep an eye on new packages. I will update readme.md then as well.

Regards,
kbs1
