### ISSUE TITLE
Is there a guide to implement VueJS client?

### ISSUE THREAD

**Issue by NightCat419** [kbs1/laravel-encrypted-api#3]
I want to use this package in my Laravel-Vue SPA.
But I cannot find the VueJS client package for your package.
Can you discuss about this?

**Comment by kbs1** [comment]
Hello,

I have a work-in progress javascript client coded as a part of another unfinished application, but the client is very basic and lacking some more advanced features (file uploads, etc).

I've uploaded the unfinished client to the nodejs client repository: https://github.com/kbs1/encrypted-api-client-nodejs - maybe you will be able to use some of the code.

If you need, I can also publish the unfinished application that used the client, but it's use should be straight-forward enough.

Please keep in mind that this project is no longer maintained, however any pull requests are apprecitated.

Regards,
kbs1

**Comment by kbs1** [comment]
Hello,

I have a work-in progress javascript client coded as a part of another unfinished application, but the client is very basic and lacking some more advanced features (file uploads, etc).

I've uploaded the unfinished client to the nodejs client repository: https://github.com/kbs1/encrypted-api-client-nodejs - maybe you will be able to use some of the code.

If you need, I can also publish the unfinished application that used the client, but it's use should be straight-forward enough.

Please keep in mind that this project is no longer maintained, however any pull requests are apprecitated.

Regards,
kbs1
